# Generated by Django 5.1.2 on 2024-10-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
