# Generated by Django 5.1.2 on 2024-10-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_home_skill_name_home_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
