# Generated by Django 5.1.2 on 2024-10-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skillcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
