# Generated by Django 5.1.2 on 2024-10-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_alter_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default='default', upload_to='skills/'),
            preserve_default=False,
        ),
    ]
